apiVersion: v1
kind: Service
metadata:
  name: ascii-artify-service
spec:
  selector:
    app: ascii-artify
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascii-artify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ascii-artify
  template:
    metadata:
      labels:
        app: ascii-artify
    spec:
      containers:
      - name: ascii-artify
        image: hashicorp/http-echo:latest
        args:
          - "-text=Hello from AsciiArtify!"
          - "-listen=:8080"
        ports:
          - containerPort: 8080
